config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelingFood</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyzvNDff7DcvGP8W61amXY8oIwNBzwFLI&libraries=places&callback=initMap" async defer>
    </script>
            
    <script>
      
      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: 21.15611, lng: -100.9325};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 3000,
          type: ['restaurant']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
          toggleBounce();
        });
          
       function toggleBounce() {
        if (marker.getAnimation() !== null) {
          marker.setAnimation(null);
        } else {
          marker.setAnimation(google.maps.Animation.BOUNCE);
        }
      }
      }
    </script>
      
  </head>
  <body class='<%= controller.controller_name %>'>
    <div id="banner">
      <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.to_s), onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>
        <%= image_tag 'logoTravelingFood', alt: 'TravekingFood' %>
		<p id="text_lol">
			La mejor comida, la encuentras aquí.
		</p>
      <span class="title"><%= @page_title %></span>
    </div>
	
    <div id="columns">
      <div id="side">
        <div id="cart">
          <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>
        </div>

        <ul>
          <li>
			<a href="http://www...."><%= t('.Inicio') %></a>
		  </li>
		  
          <li>
			<%= link_to "Ordenes", orders_path%>
		  </li>
          <li>
			<a href="http://www..../news"><%= t('.Noticias') %></a>
		  </li>
          <li>
			<a href='http://www..../contact'><%= t('.Contacto') %></a>
		  </li>
		  <li>
			<a data-toggle="modal" data-target="#myModal">QR</a>
		  </li>
		  <li>
			<a data-toggle="modal" data-target="#myModalDos">Información</a>
		  </li>
        </ul>
      </div>

      <% if session[:user_id] %>
        <ul>
            <li><%= link_to 'Ordenes', orders_path %></li>
            <li><%= link_to 'Productos', products_path %></li>
          <li><%= link_to 'Usuarios', users_path %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
      <div id="main">
        <%= yield %>
          <div id="map"></div>
        
      </div>
      </div>
    </div>
	
	
	<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog modal-lg">
		  <div class="modal-content">
			<div class="modal-header">
			  <button type="button" class="close" data-dismiss="modal">&times;</button>
			  <h4 class="modal-title">Realidad aumentada</h4>
			</div>
			<div class="modal-body">
			  <center id="doss">
					<%= image_tag "http://marcheloo.com/Images/logo/159%20%20nana%20pancha.jpg", :alt => "Facebook", :title => "Facebook"%>
			  </center>
			</div>
			<div class="modal-footer">
			  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		  </div>
		</div>
	</div>

	
	<div class="modal fade" id="myModalDos" role="dialog">
		<div class="modal-dialog modal-lg">
		  <div class="modal-content">
			<div class="modal-header">
			  <button type="button" class="close" data-dismiss="modal">&times;</button>
			  <h1 class="modal-title">Información de los restauranes</h1>
			</div>
			<div class="modal-body">
				
				<p><h4>El Carruaje Restaurante</h4>
					<%= image_tag "http://www.viajaraitalia.com/wp-content/uploads/2012/06/hoteles-4-estrellas-napoles.png", :alt => "Facebook", :title => "Facebook"%>
				<b>Parrilla</b><br/>Dolores Hidalgo Cuna de la Independencia Nacional, Gto.Ambiente relajado · Buenos cócteles
				<br/>
				<%= image_tag "https://lh3.googleusercontent.com/-l7HgvIAaUvg/V_LZ_PLVfEI/AAAAAAAAAys/Zp4hkmXrfTwOWMiBw8IKyFPdy1XUsBCqwCJkC/w99-h99-n-k-no/", :alt => "Facebook", :title => "Facebook"%>
				</p>
			  
				<p><h4>Nana Pancha Pizza y Café</h4>
					<%= image_tag "https://vignette2.wikia.nocookie.net/gunsnroses/images/e/e4/4.5_estrellas.png/revision/latest?cb=20100905204438&path-prefix=es", :alt => "Facebook", :title => "Facebook"%>
				<b>Cafetería</b><br/>Dolores Hidalgo Cuna de la Independencia Nacional, Gto. Ambiente relajado · Agradable · Informal
				<br/>
				<%= image_tag "https://lh3.googleusercontent.com/-UMKGtQf0Wkg/WNsmETqowCI/AAAAAAAAAXI/gx3F0DRKFRoGNlBWceYr8xflsWBy6fIaACLIB/w99-h99-n-k-no/", :alt => "Facebook", :title => "Facebook"%>
				</p>
				
				<p><h4>Damonica</h4>
					<%= image_tag "https://vignette2.wikia.nocookie.net/gunsnroses/images/e/e4/4.5_estrellas.png/revision/latest?cb=20100905204438&path-prefix=es", :alt => "Facebook", :title => "Facebook"%>
				<b>Cafetería</b><br/>Dolores Hidalgo Cuna de la Independencia
				<br/>
				<%= image_tag "https://lh3.googleusercontent.com/-UMKGtQf0Wkg/WNsmETqowCI/AAAAAAAAAXI/gx3F0DRKFRoGNlBWceYr8xflsWBy6fIaACLIB/w99-h99-n-k-no/", :alt => "Facebook", :title => "Facebook"%>
				</p>
			  
			</div>
			<div class="modal-footer">
			  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		  </div>
		</div>
	</div>
	
  </body>
</html>
 <!--Galeria de comida dolorence API AIzaSyC5z87QigtMXQJjCW9cX2245_hpDBCVRyA, AIzaSyCyzvNDff7DcvGP8W61amXY8oIwNBzwFLI
lat: 21.15611, lng: -100.9325-->